name    = "SafeREPL"
uuid    = "5e6a0ad9-8e90-40fa-86b1-deb43b8cfda7"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.0.1"

[deps]
REPL         = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SwapLiterals = "b9c42661-4c44-44aa-8691-47710c88d134"

[compat]
julia = "1.5"
