name    = "SwapLiterals"
uuid    = "b9c42661-4c44-44aa-8691-47710c88d134"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.1"

[extras]
BitIntegers   = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"
Test          = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BitIntegers", "SaferIntegers", "Test"]

[compat]
julia = "1.1"
